image: $CI_REGISTRY/images/go:latest

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin

stages:
  - build
  - deploy

compile:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/cloudflare
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  script:
    - envsubst < cloudflare.tpl > cloudflare.yaml
    # - kubectl create --namespace default deployment cloudflare --image=$CI_REGISTRY_IMAGE:latest
    - kubectl create --namespace default -f cloudflare.yaml
  environment:
    name: production
    url: https://$CI_ENVIRONMENT_SLUG.$EXTERNAL_URL/
  only:
    - master
